### ISSUE TITLE
visit_detail_id missing in new BCLink Export 

### ISSUE THREAD

**Issue by calmacx** [CO-CONNECT/co-connect-tools#69]
The CI is failing for PR #68 because visit_detail_id has been dropped in condition_occurrence the new BCLink export produced by @spco  and when comparing with the expected output, it has found differences.

According to the webpage:
https://ohdsi.github.io/CommonDataModel/cdm531.html#CONDITION_OCCURRENCE
it should be present 

Looks to have also been dropped in other tables (measurement, observation)

Probably not important

**Comment by spco** [comment]
Good spot. I'm presuming this isn't important, and this is on BCLink to fix if they want/need to. I'm happy if you want to change the test dataset.

**Comment by calmacx** [comment]
expected outputs updated in #68
